//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mağaza_Ürün_Takip_Sistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.SATISLAR = new HashSet<SATISLAR>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string marka { get; set; }
        public Nullable<int> stok { get; set; }
        public Nullable<decimal> alisfiyat { get; set; }
        public Nullable<decimal> satisfiyat { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISLAR> SATISLAR { get; set; }
    }
}
